### ISSUE TITLE
`ssh_authorized_keys` in `--cloud-init` breaks Multipass communicating with the instance

### ISSUE THREAD

**Issue by Saviq** [CanonicalLtd/multipass#965]
I've been trying to use cloud init files but you still need to pass an `ssh_authorized_keys` for multipass so you can run `multipass info node_name`. Otherwise it cannot communicate with the machines it created. Right now I have it hardcoded in my cloud-init file but it would be better to dynamically create the cloud init file with the right multipass cert.

_Originally posted by @aemadrid in https://github.com/CanonicalLtd/multipass/issues/913#issuecomment-521051812_

---

@aemadrid can you please describe what you're doing exactly and include examples of `cloud-init` files? If you're able to "break" the connection between Multipass and its instances, that's definitely a bug.

**Comment by aemadrid** [comment]
Let's say I create a vm using a cloud-init file like this:

```
echo "users:
  - name: deploy
    sudo:  ALL=(ALL) NOPASSWD:ALL
    ssh_authorized_keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC9r/vyaaV03LwDEo/QKbGCRql6EfWobK5nMf+jifuNF91a96xz6lyUOAGuxDguGZ1JxK/FBL8Q5VoZptk2yqHhYRx3IRDJHpPKDlut6p+6KnD/+uvUzHZLZgRSuLo7RJLY/yPXUvLQ4ztpM5zTzcHK1LU/mbrKH/3ytsJywRPbRxh5LmuKs0kxn19Wur1Oj1y765IDxEnpb3G8CaNesyhm7nBU8BOzq8tCphnBKecvrsyW0snHtFC0MSml+Fed/N1/o9YfhIFbgcpH60m45XEHJJg0aVhB0Gz1am2VIo6DHBXMvPD+GvqCUDrq+GwJBaefys/iwiaOY4Nj/GaLKmNZ deploy@example.com
system_info:
  default_user:
    name: deploy" > ci.yml

multipass launch -n test --cloud-init ci.yml
```

Then I cannot shell into it from multipass:

```
multipass shell test
shell failed: ssh failed to authenticate: 'Socket error: disconnected'
```

Or get info from multipass:

```
multipass info test
info failed: ssh failed to authenticate: 'Socket error: disconnected'
```

But I can ssh into the vm with the `deploy` user:

```
ssh deploy@192.168.64.6
deploy@test:~$
```
